---
title: Miriam - Dolços i Pasitssos
timezone: Europe/Madrid
url: https://miriam.cat
permalink: pretty
plugins:
  - jekyll-sitemap
excerpt_separator: <!--more-->
collections:
  serveis:
    output: true
    permalink: /:collection/:name
  receptes:
    output: true
    permalink: /:collection/:name
sass:
    sass_dir: _sass
    style: compressed