---
title: miriamdolcets
timezone: Europe/Madrid
url: https://miriam.cat
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-postcss
excerpt_separator: <!--more-->
collections:
  galetes:
    output: true
    permalink: /:collection/:name
  serveis:
    output: true
    permalink: /:collection/:name
  receptes:
    output: true
    permalink: /:collection/:name
sass:
    sass_dir: _sass
    style: compressed