---
title: Miriam - Dolços & Pasitssos
timezone: Europe/Madrid
url: https://miriam.cat
permalink: pretty
plugins:
  - jekyll-sitemap
excerpt_separator: <!--more-->
collections:
  projectes:
    output: true
    permalink: /:collection/:name
  serveis:
    output: true
    permalink: /:collection/:name
  clients:
    output: true
    permalink: /:collection/:name
prose:
  siteurl: https://miriam.cat
  media: uploads
  ignore:
    - index.md
    - 404.md
    - .gitignore
    - favicon.ico
    - CNAME
    - style.css
    - _config.yml
    - /_layouts
    - /_plugins
    - /_includes
    - /assets
    - /_includes